language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build --target development -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed abmesamesa/udagram-api-feed:latest
  - docker build --target development -t udagram-api-users ./udagram-api-users
  - docker tag udagram-api-users abmesamesa/udagram-api-users:latest
  - docker build --target development -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend abmesamesa/udagram-frontend:latest
  - docker build -t api-reverse-proxy ./api-reverse-proxy
  - docker tag api-reverse-proxy abmesamesa/api-reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push abmesamesa/udagram-api-feed
  - docker push abmesamesa/udagram-api-users
  - docker push abmesamesa/udagram-frontend
  - docker push abmesamesa/api-reverse-proxy
