apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-reverse-proxy
  labels:
    app: api-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-reverse-proxy
  template:
    metadata:
      labels:
        app: api-reverse-proxy
    spec:
      containers:
        - name: api-reverse-proxy
          imagePullPolicy: Always
          image: abmesamesa/api-reverse-proxy
          resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "150m"
          ports:
            - containerPort: 8080
