apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-reverse-proxy
  name: api-reverse-proxy
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: api-reverse-proxy
  type: LoadBalancer
