version: '3.9'
services:
  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 8000:80
    networks:
      - application
      - front
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_USER}
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d
    networks:
      - admin
      - front

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - admin
    depends_on:
      - database

networks:
  admin:
  application:
  front:
    external:
      name: front-external
